"""empty message

Revision ID: e88df5a3b683
Revises:
Create Date: 2024-07-04 09:07:55.777783

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e88df5a3b683"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund",
        sa.Column("fund_id", sa.UUID(), nullable=False),
        sa.Column("name_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("title_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("description_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("welsh_available", sa.Boolean(), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("fund_id", name=op.f("pk_fund")),
        sa.UniqueConstraint("short_name", name=op.f("uq_fund_short_name")),
    )
    op.create_table(
        "round",
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.UUID(), nullable=False),
        sa.Column("title_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("opens", sa.DateTime(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("assessment_start", sa.DateTime(), nullable=True),
        sa.Column("reminder_date", sa.DateTime(), nullable=True),
        sa.Column("assessment_deadline", sa.DateTime(), nullable=True),
        sa.Column("prospectus", sa.String(), nullable=False),
        sa.Column("privacy_notice", sa.String(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["fund_id"], ["fund.fund_id"], name=op.f("fk_round_fund_id_fund")),
        sa.PrimaryKeyConstraint("round_id", name=op.f("pk_round")),
        sa.UniqueConstraint("fund_id", "short_name", name=op.f("uq_round_fund_id")),
    )
    op.create_table(
        "section",
        sa.Column("round_id", sa.UUID(), nullable=True),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("name_in_apply_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("Template Name", sa.String(), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["round_id"], ["round.round_id"], name=op.f("fk_section_round_id_round")),
        sa.PrimaryKeyConstraint("section_id", name=op.f("pk_section")),
    )
    op.create_table(
        "form",
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("name_in_apply_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("Template Name", sa.String(), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("section_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["section_id"], ["section.section_id"], name=op.f("fk_form_section_id_section")),
        sa.PrimaryKeyConstraint("form_id", name=op.f("pk_form")),
    )
    op.create_table(
        "page",
        sa.Column("form_id", sa.UUID(), nullable=True),
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("name_in_apply_json", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("Template Name", sa.String(), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("form_index", sa.Integer(), nullable=True),
        sa.Column("display_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["form.form_id"], name=op.f("fk_page_form_id_form")),
        sa.PrimaryKeyConstraint("page_id", name=op.f("pk_page")),
    )
    op.create_table(
        "component",
        sa.Column("page_id", sa.UUID(), nullable=True),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("hint_text", sa.String(), nullable=True),
        sa.Column("options", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TEXT_FIELD",
                "FREE_TEXT_FIELD",
                "EMAIL_ADDRESS_FIELD",
                "UK_ADDRESS_FIELD",
                "HTML",
                "YES_NO_FIELD",
                name="componenttype",
            ),
            nullable=True,
        ),
        sa.Column("Template Name", sa.String(), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("page_index", sa.Integer(), nullable=True),
        sa.Column("conditions", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["page.page_id"], name=op.f("fk_component_page_id_page")),
        sa.PrimaryKeyConstraint("component_id", name=op.f("pk_component")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("component")
    op.drop_table("page")
    op.drop_table("form")
    op.drop_table("section")
    op.drop_table("round")
    op.drop_table("fund")
    # ### end Alembic commands ###
