"""empty message

Revision ID: 64b2de15add2
Revises: 
Create Date: 2024-07-02 14:00:05.811033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64b2de15add2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('name_json', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('title_json', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('description_json', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('welsh_available', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('audit_info', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('fund_id', name=op.f('pk_fund')),
    sa.UniqueConstraint('short_name', name=op.f('uq_fund_short_name'))
    )
    op.create_table('round',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('title_json', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('opens', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('assessment_start', sa.DateTime(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('assessment_deadline', sa.DateTime(), nullable=True),
    sa.Column('prospectus', sa.String(), nullable=False),
    sa.Column('privacy_notice', sa.String(), nullable=False),
    sa.Column('audit_info', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], name=op.f('fk_round_fund_id_fund')),
    sa.PrimaryKeyConstraint('round_id', name=op.f('pk_round')),
    sa.UniqueConstraint('fund_id', 'short_name', name=op.f('uq_round_fund_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round')
    op.drop_table('fund')
    # ### end Alembic commands ###
